package exerelin.skills.scripts;

public class ExerelinSkillData {

	public static final float FACTION_APTITUDE_STATION_EFFICIENCY_INCREASE_PERCENTAGE = 1f;
	
	public static final float FACTION_ACTIVEDIPLOMACY_EFFECT_ITEM_AVAILABILITY_BONUS_PERECENTAGE= 1f;
	public static final float FACTION_ACTIVEDIPLOMACY_PERK_NEW_ITEM = 1;
	public static final float FACTION_ACTIVEDIPLOMACY_PERK_ITEM_REUSE_CHANCE = 25f;

    public static final float FACTION_FLEETCREWTRAINING_EFFECT_EXPERIENCE_BONUS_PERCENTAGE = 2f;

    public static final float FACTION_FLEETDEPLOYMENT_EFFECT_RESOURCECOST_REDUCTION_PERCENTAGE = 1f;
    public static final float FACTION_FLEETDEPLOYMENT_PERK_ELITE_SHIP_CHANCE_BONUS_PERCENTAGE = 25f;

    public static final float FACTION_PASSIVEDIPLOMACY_EFFECT_RELATIONSHIP_BONUS_PERCENTAGE = 1f;
    public static final float FACTION_PASSIVEDIPLOMACY_PERK_ALLIANCE_BETRAYAL_REDUCTION_PERCENTAGE = 25f;

    public static final float FACTION_STATIONINDUSTRY_EFFECT_STATION_EFFICIENCY_BONUS_PERCENTAGE = 1f;
    public static final float FACTION_STATIONINDUSTRY_PERK_STATION_RESOURCE_CAP_BONUS_PERCENTAGE = 100f;
    public static final float FACTION_STATIONINDUSTRY_PERK_ADDITIONAL_MINING_FLEET = 1;
}









